services:
  presentation:
    image: presentation
    build:
      context: .
      dockerfile: presentation/Dockerfile
    networks:
      - ecommerce_network


networks:
  ecommerce_network:
    external: true